---
name: Genome-Model-Tools-Music
version: 0.02
author: []
abstract: find mutations of significance in cancer
license: lgpl
resources:
  license: http://opensource.org/licenses/lgpl-license.php
build_requires:
  Genome: 0.06
  UR: 0.33
requires:
  Genome: 0.06
  Statistics::Distributions: ''
  Text::CSV_XS: ''
configure_requires:
  Module::Build: 0.340201
provides:
  Genome::Model::Tools::Music:
    file: lib/Genome/Model/Tools/Music.pm
    version: 0.02
  Genome::Model::Tools::Music::Base:
    file: lib/Genome/Model/Tools/Music/Base.pm
    version: 0
  Genome::Model::Tools::Music::Bmr:
    file: lib/Genome/Model/Tools/Music/Bmr.pm
    version: 0
  Genome::Model::Tools::Music::Bmr::CalcBmr:
    file: lib/Genome/Model/Tools/Music/Bmr/CalcBmr.pm
    version: 0
  Genome::Model::Tools::Music::Bmr::CalcCovg:
    file: lib/Genome/Model/Tools/Music/Bmr/CalcCovg.pm
    version: 0
  Genome::Model::Tools::Music::ClinicalCorrelation:
    file: lib/Genome/Model/Tools/Music/ClinicalCorrelation.pm
    version: 0
  Genome::Model::Tools::Music::CosmicOmim:
    file: lib/Genome/Model/Tools/Music/CosmicOmim.pm
  Genome::Model::Tools::Music::MutationRelation:
    file: lib/Genome/Model/Tools/Music/MutationRelation.pm
    version: 0
  Genome::Model::Tools::Music::PathScan:
    file: lib/Genome/Model/Tools/Music/PathScan.pm
    version: 0
  Genome::Model::Tools::Music::PathScan::CombinePvals:
    file: lib/Genome/Model/Tools/Music/PathScan/CombinePvals.pm
  Genome::Model::Tools::Music::PathScan::PathScan:
    file: lib/Genome/Model/Tools/Music/PathScan/PathScan.pm
  Genome::Model::Tools::Music::PathScan::PopulationPathScan:
    file: lib/Genome/Model/Tools/Music/PathScan/PopulationPathScan.pm
  Genome::Model::Tools::Music::Pfam:
    file: lib/Genome/Model/Tools/Music/Pfam.pm
    version: 0
  Genome::Model::Tools::Music::Play:
    file: lib/Genome/Model/Tools/Music/Play.pm
    version: 0
  Genome::Model::Tools::Music::Proximity:
    file: lib/Genome/Model/Tools/Music/Proximity.pm
    version: 0
  Genome::Model::Tools::Music::Smg:
    file: lib/Genome/Model/Tools/Music/Smg.pm
    version: 0
generated_by: Module::Build version 0.340201
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
